### ISSUE TITLE
Branch length issues

### ISSUE THREAD

**Issue by theosanderson** [jmcbroome/BTE#18]
I'm not entirely sure if this is an UShER Q or a BTE question, but here goes. I've been writing out trees from a protobuf (`gisaidAndPublic.2023-05-11.masked.gisaidNames.pb.gz`) with `write_newick`. Something I've encountered is that occasionally branches in the newick output have lengths that don't relate to their number of mutations in the MAT. E.g. `node_1901667` in that MAT has a bunch of mutations, but length 0 in the newick output. Debugging, I find it also has similar issues in the MAT object:

```
id: node_1901667
level: 36
parent: node_1901664
children: [children here]
mutations: ['T5213C', 'G8366A', 'G10981A', 'G11128A', 'A12682G', 'C16173T', 'G19254A', 'C22350T', 'C22851T', 'A25363G', 'C26645T', 'G26828A', 'G28631A']
annotations: ['', '']
branch length: 0.0
```

I remember that the Newick string in the MAT can sometimes (often?) have issues like this, so taxoniumtools counts up the mutations manually.

Could you clarify how all this works? And I guess ideally the newick export would correspond to the number of mutations?

Thanks!

**Comment by theosanderson** [comment]
Ah, sorry for a failure to read the docs, I suspect this may be about: `retain_original_branch_len `

**Comment by theosanderson** [comment]
OK, that was it. I'm going to close this because I have the solution (set `retain_original_branch_len ` to False). A minor suggestion is that defaulting to that might make things more obvious. But maybe that would break too many existing things. Sorry for the noise!

**Comment by jmcbroome** [comment]
Glad you were able to find a workaround on your own. I am curious as to why those branch lengths were incorrectly initialized in the first place, though, might reflect some deeper data issues. With regards to your suggestion, I'd like BTE to be able to support arbitrary branch lengths so that it can function with non-parsimony MATs, so I'm going to keep retain_original_branch_length with the default of True, so future users don't accidentally lose data. Better to fix whatever is causing misaligned branch lengths in regular MATs then default apply a patch that could be damaging in other cases. 

Thanks for raising the issue, in any case. I'll keep an eye out for related problems in our MATs.
